services:
  pyspark-runner: &pyspark-base
    build:
      context: .
      dockerfile: docker/pyspark/Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace

  pyspark-notebook:
    <<: *pyspark-base
    command:
      - jupyter
      - lab
      - --ip=0.0.0.0
      - --port=8888
      - --no-browser
      - --allow-root
      - --ServerApp.token=spark-optimization
      - --ServerApp.password=
    ports:
      - "8888:8888"
